### ISSUE TITLE
Streaming.h

### ISSUE THREAD

**Issue by bavelt** [JChristensen/MCP9800#1]
Hello,
I have tried this sketch, but it is missing the streaming.h.
When I download  this from some site of internet, the result is a lot of strange characters on the screen, refreshing every second.

**Comment by JChristensen** [comment]
Hello,
What sketch are you trying?

**Comment by bavelt** [comment]
Sketch MCP9800

In the meantime I discovered that descending the 115200 to 9600 baudrate solves the strange characters on the monitor.

 

I have a problem with the MCP9801. The TEMP register is a word (also 2 bytes). But the second (lower)  byte always reads 255,  so all the bits are “1”.
I tried a lot (usually I program with MikroBasic, but can’t solve this issue). That is why I tried the sensor with my Arduino.

Do you perhaps recognize this problem of second byte is always high?


Thx!

 

bavelt

 








 

Van: Jack Christensen [mailto:notifications@github.com] 
Verzonden: zaterdag 18 januari 2020 14:06
Aan: JChristensen/MCP9800
CC: bavelt; Author
Onderwerp: Re: [JChristensen/MCP9800] Streaming.h (#1)

 

Hello,
What sketch are you trying?

**Comment by JChristensen** [comment]
I still don't know what sketch you are referring to. Have you tried the [MCP9800_EX1 example sketch](https://github.com/JChristensen/MCP9800/blob/master/examples/MCP9800_EX1/MCP9800_EX1.ino)?

I don't remember ever seeing the problem you describe, with one byte being all ones.

**Comment by bavelt** [comment]
Hi Jack,
Yes, it is the MCP9800_EXT sketch.

The sketch works now.
In the meantime I discovered the solution: In the I2c Protocol after the first byte read you have to send an ACK and after the second byte an NAK.
I reversed this.

thx!
