### ISSUE TITLE
Not working on AVR

### ISSUE THREAD

**Issue by MrTvda** [JChristensen/MCP9800#2]
Hi there,

Is this code compatible with AVR?
While I'm including this library my code gets stuck on a function except the start function.

**Comment by JChristensen** [comment]
Yes it is; I work with AVR exclusively.
Start function? The library has no function by that name.
Perhaps there is a problem with the I2C bus. I would suggest trying [this example sketch](https://github.com/JChristensen/MCP9800/blob/master/examples/MCP9800_EX1/MCP9800_EX1.ino).

**Comment by MrTvda** [comment]
The example is working but I have to use only the AVR to program my project.
I mean the begin() function works but when I want to read in AVR the temperature the code hangs.

**Comment by JChristensen** [comment]
I don't understand what you mean by "use only the AVR to program my project."

**Comment by MrTvda** [comment]
I can't use the setup and loop of arduino, I have to work with the library <avr/io.h>

**Comment by JChristensen** [comment]
Are you using the Arduino IDE, or something else?

**Comment by MrTvda** [comment]
I use Platform.io, not the Arduino IDE

**Comment by JChristensen** [comment]
I've never used Platform.io, so you have me at a disadvantage. Can you post some example code? Hopefully 100 lines or less.

**Comment by MrTvda** [comment]
This is how it looks like

#include <avr/io.h>
#include <util/delay.h>
#include "hd44780.h"
#include "mcp9800.h"

MCP9800 mcp9800;

int main(void) {
  lcd_init();
  lcd_clrscr();
  // lcd_puts("Testing");
  mcp9800.begin();

  // _delay_ms(1000);

  while (1) {

    int c = mcp9800.readTempC16(AMBIENT);
    mcp9800.writeTempC2(AMBIENT, c);
    lcd_puts("Hello");
    _delay_ms(1000);
  }

  return 1;
}

**Comment by JChristensen** [comment]
Well if there is no access to Arduino libraries, it's not going to work. The MCP9800 library requires the Arduino Wire.h library.
